<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yaml</string>
	</array>
	<key>name</key>
	<string>MiniYAML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#node</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>node-removal</key>
		<dict>
			<key>match</key>
			<string>^\t+(-.+?)(?=@|:)</string>
			<key>name</key>
			<string>keyword.control.miniyaml</string>
		</dict>
		<key>node-identifier</key>
		<dict>
			<key>match</key>
			<string>(?<=\S)(@\S+)(?=:(?= |$))</string>
			<key>name</key>
			<string>entity.name.type.miniyaml</string>
		</dict>
		<key>block-pair</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#node-removal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\t*\S[^@:]*(?=@|: |:$)</string>
					<key>name</key>
					<string>entity.name.tag.miniyaml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:(?= |$)</string>
					<key>name</key>
					<string>punctuation.separator.key-value.mapping.miniyaml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#node-identifier</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>(?:(^[ \t]*)|[ \t]+)(?=#(\p{Print}|\t)*$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.miniyaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.miniyaml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.miniyaml</string>
				</dict>
			</array>
		</dict>
		<key>flow-scalar-plain-out</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#flow-scalar-plain-out-implicit-type</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)
                          [^\s,]
                        | [?:-] \S
                    </string>
					<key>end</key>
					<string>(?x)
                        (?=
                              \s* $
                            | \s+ \#
                        )
                    </string>
					<key>name</key>
					<string>string.unquoted.plain.out.miniyaml</string>
				</dict>
			</array>
		</dict>
		<key>flow-scalar-plain-out-implicit-type</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.miniyaml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.miniyaml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.miniyaml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.miniyaml</string>
						</dict>
						<key>5</key>
						<dict>
							<!-- RGB(A) color hex value -->
							<key>name</key>
							<string>constant.numeric.numeric.miniyaml</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.miniyaml</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.miniyaml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
                        (?x:
                            (true|True|TRUE|false|False|FALSE)
                            | (
                                (?:
                                    ( [-+]? (?: 0|[1-9][0-9_]*) ) c ( 0|[1-9][0-9_]* ) # (base 10)
                                )
                              )
                            | (
                                (?:
                                    [0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]
                                )
                              )
                            | (
                                (?:
                                    [-+]? (?: 0|[1-9][0-9_]*) # (base 10)
                                )
                              )
                            | (
                                (?x:
                                    [-+]? (?: [0-9] [0-9_]*)? \. [0-9.]* (?: [eE] [-+] [0-9]+)? # (base 10)
                                )
                              )
                        )
                    </string>
				</dict>
			</array>
		</dict>
		<key>node</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-pair</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#flow-scalar-plain-out</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.miniyaml</string>
	<key>uuid</key>
	<string>DAA404CB-656F-4D24-AA2B-E4D5EAB984D4</string>
</dict>
</plist>
